### ISSUE TITLE
[Python 3.11 deprecation] Stop using `importlib.resources.path`

### ISSUE THREAD

**Issue by webknjaz** [certifi/python-certifi#183] opened 2022-01-12 01:07 UTC
I'm observing
```console
E   DeprecationWarning: path is deprecated. Use files() instead. Refer to importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
```
This is caused by `import requests` which in turn calls `certs.where()`. The deprecation warning is caused by https://github.com/certifi/python-certifi/blob/ff23c47/certifi/core.py#L38 in the certify-land.

Full CI log: https://github.com/cherrypy/cheroot/runs/4783241877?check_suite_focus=true#step:17:535

**Comment by sigmavirus24** [comment] 2022-01-12 13:33
Duplicate of #170. In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Closed by sigmavirus24** 2022-01-12 13:33 UTC

**Comment by webknjaz** [comment] 2022-01-12 13:39
Ah, I missed the closed one.

FWIW, for those coming here from Google, here's what you can do in the pytest configuration when running it with `filterwarnings = error` under Python 3.11, per the best practices:
```ini
filterwarnings =
  error

  # FIXME: drop once certifi fixes their use of `importlib.resources`
  # Ref: https://github.com/certifi/python-certifi/issues/183
  ignore:path is deprecated. Use files.. instead. Refer to https.//importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.:DeprecationWarning:certifi.core
```
