### ISSUE TITLE
Certificate error with google secure connection

### ISSUE THREAD

**Issue by uolter** [certifi/python-certifi#37] opened 2016-04-26 10:46 UTC
I am running 

python 2.7.6

certifi==2016.2.28
requests==2.9.1

and this simple call does not work anymore:
python -c "import requests; requests.get('https://google.com', verify=True)"

>> .....
.........
SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

while it works fine with this certificate:

REQUESTS_CA_BUNDLE='/etc/ssl/certs/ca-certificates.crt'  python -c 'import requests; requests.get("https://google.com")'

Which is the best way to sort out the issue since this is also part of my Django application working with social-python which stopped to work due to this issue a couple of days ago.

Thanks,

Walter

**Comment by Lukasa** [comment] 2016-04-26 10:48
This is a duplicate of #26: the issue is almost certainly that your platform does not support cross-signed certificates due to OpenSSL being too old. This is a problem, because the certifi strong bundle has removed all 1024-bit root certificates because they're dangerously insecure, whereas your distribution has almost certainly left them in place because they won't upgrade their OpenSSL.

Various mitigations are discussed in #26. The easiest is to pass `certifi.old_where()` to `verify`. Alternatively, you can set the REQUESTS_CA_BUNDLE variable to the result of `cerifi.old_where()`.

**Closed by Lukasa** 2016-04-26 10:48 UTC
