### ISSUE TITLE
expired cert in bundle

### ISSUE THREAD

**Issue by tsgit** [certifi/python-certifi#165] opened 2021-10-05 19:01 UTC
Hi,

the current certifi bundle (certifi==2021.5.30) contains a cert which expired on 9/30/21 .

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            44:af:b0:80:d6:a3:27:ba:89:30:39:86:2e:f8:40:6b
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: O = Digital Signature Trust Co., CN = DST Root CA X3
        Validity
            Not Before: Sep 30 21:12:19 2000 GMT
            Not After : Sep 30 14:01:15 2021 GMT
        Subject: O = Digital Signature Trust Co., CN = DST Root CA X3
....
```

This affects e.g. CentOS 7.9, Python 2.7.5, requests==2.26.0 -- which fails to verify Letsencrypt issued certificates (ISRG Root X1).

It doesn't impact verification of Letsencrypt issued certificates with Python 2.7.18 (Fedora 34). So handling of expired certificates in the bundle is dependent on specific installation and/or version of Python.

Cheers
T.

**Comment by Lukasa** [comment] 2021-10-05 19:02
Dupe of #162.

**Closed by Lukasa** 2021-10-05 19:02 UTC
