### ISSUE TITLE
Removal of Thawte?

### ISSUE THREAD

**Issue by devdazed** [certifi/python-certifi#27] opened 2015-09-08 16:11 UTC
I see in the last release you removed Thawte from the bundle completely, Any reason for this?  This has broken all requests to any service using Thawte including OutbrainAPI and Mandrill.

**Comment by Lukasa** [comment] 2015-09-08 16:19
I did not remove Thawte: I removed their 1024-bit root. This is a dupe of #26.

**Closed by Lukasa** 2015-09-08 16:19 UTC
