### ISSUE TITLE
certifi.io webserver misconfigured?

### ISSUE THREAD

**Issue by paulmueller** [certifi/python-certifi#128] opened 2020-06-03 07:52 UTC
I get a "403 forbidden" when trying to access https://certifi.io.
I would suggest/recommend migrating the documentation to readthedocs.io

**Comment by dbjock** [comment] 2021-06-24 14:04
This issue is still ongoing. 
https://certifiio.readthedocs.io/en/latest/ redirects to https://certifi.io/en/latest/ which is "403 Forbidden"

**Comment by sigmavirus24** [comment] 2021-08-28 01:17
Duplicate of https://github.com/certifi/certifi.io/issues/24

**Closed by sigmavirus24** 2021-08-28 01:17 UTC
