### ISSUE TITLE
GeoTrust Global CA erroneously removed?

### ISSUE THREAD

**Issue by tarmath** [certifi/python-certifi#144] opened 2020-12-11 05:07 UTC
Latest release seems to be missing the GeoTrust Global CA (amongst others)

Unfortunately, commit offers no explanation:

https://github.com/certifi/python-certifi/commit/45a64658872a94a83c4b70fce02a96f0f29895e6#diff-e1f673cf40a49b35c77f0550d8d3f940471f098e8e102bccc0ad72d05cf13d87

Was this perhaps a mistake? 

They still do seem to be used by Mozilla:

 * https://wiki.mozilla.org/CA/Included_Certificates 
 * https://hg.mozilla.org/releases/mozilla-beta/file/tip/security/nss/lib/ckfw/builtins/certdata.txt#l1145

**Comment by alex** [comment] 2020-12-11 05:08
Dupe of #142

**Closed by alex** 2020-12-11 05:08 UTC
