### ISSUE TITLE
HTTP 403 error on https://certifi.io/ 

### ISSUE THREAD

**Issue by pombredanne** [certifi/python-certifi#132] opened 2020-07-06 06:39 UTC
and also on https://certifiio.readthedocs.io/ that redirects there

**Comment by jaraco** [comment] 2020-10-21 15:40
I noticed this when clicking Homepage from https://pypi.org/project/certifi.

**Comment by guerzon** [comment] 2020-11-04 07:10
Hi there,

I just wanted to let you know that https://certifi.io/en/latest/ is still down.

Cheers.

**Comment by vyx-alex-willisson** [comment] 2021-07-14 15:35
Still down

**Comment by jaraco** [comment] 2021-07-15 02:16
This also looks to be a dupe of #128.

**Comment by sigmavirus24** [comment] 2021-08-28 01:18
Duplicate of https://github.com/certifi/certifi.io/issues/24

**Closed by sigmavirus24** 2021-08-28 01:18 UTC

**Comment by faiyeah** [comment] 2021-10-05 03:20
It is still down till now

**Comment by hugovk** [comment] 2021-10-08 11:32
Please see PR https://github.com/certifi/python-certifi/pull/145 for a fix.

**Comment by tucked** [comment] 2021-12-01 18:47
This is still happening for me.
