### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by goinnn** [certifi/python-certifi#40] opened 2016-05-25 09:30 UTC
With certifi installed:

```
import requests
requests.get('https://maps.googleapis.com/maps/api/geocode/json?address=%s' % '58 Rue de la Verrerie, 75004 Paris, Francia')
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

Without certifi installed:

```
import requests
requests.get('https://maps.googleapis.com/maps/api/geocode/json?address=%s' % '58 Rue de la Verrerie, 75004 Paris, Francia')
<Response [200]>
```

**Comment by Lukasa** [comment] 2016-05-25 09:32
Thanks for this!

This is a duplicate of #26: essentially, your OpenSSL is sufficiently old that it doesn't like the use of cross-signed TLS root certificates. If you pass `verify=certifi.old_where()` into your `requests.get` call you'll find that everything works.

**Closed by Lukasa** 2016-05-25 09:32 UTC

**Comment by goinnn** [comment] 2016-05-25 09:35
Thanks!
