### ISSUE TITLE
Certifi link is broken 

### ISSUE THREAD

**Issue by Badboy1307** [certifi/python-certifi#155] opened 2021-07-20 18:22 UTC
The link for Certifi. Please correct it.  The below image justifies the same.

![image](https://user-images.githubusercontent.com/60011091/126375699-8436c1c5-d073-44f4-a906-2c711e76b962.png)

**Comment by sigmavirus24** [comment] 2021-07-20 22:31
Duplicate of #132 

In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Closed by sigmavirus24** 2021-07-20 22:31 UTC
