### ISSUE TITLE
Google Maps API Certificate Error...

### ISSUE THREAD

**Issue by cbrum11** [certifi/python-certifi#68] opened 2017-08-31 14:46 UTC
Receiving certificate error when trying to use Google Maps API.  Fixed the issue by rolling back certifi but wanted to make you aware...

See: [THIS THREAD](https://github.com/googlemaps/google-maps-services-python/issues/191#issuecomment-326192693)

**Comment by Lukasa** [comment] 2017-08-31 14:53
This is almost certainly a duplicate of #26. Please update your OpenSSL.

**Closed by Lukasa** 2017-08-31 14:53 UTC

**Comment by cbrum11** [comment] 2017-08-31 15:16
Thanks.  Will update and get back with the verdict.

**Comment by cbrum11** [comment] 2017-08-31 15:34
Good news.  Problem solved.  For anyone using Python and wanting more details, the following steps should fix your problem and allow you to use latest certifi version.

`pip install pyOpenSSL`

`pip install requests[security]`

To check that everything is the latest and greatest...

`pip list`
