### ISSUE TITLE
Remove expired "DST Root CA X3"

### ISSUE THREAD

**Issue by gloomytrousers** [certifi/python-certifi#182] opened 2021-12-06 20:08 UTC
The "DST Root CA X3" certificate included in cacert.pem is expired (Sep 2021), and known to cause issues validating Let's Encrypt certificates (e.g. [this](https://bugzilla.redhat.com/show_bug.cgi?id=2029153)). Please could it be removed?

**Comment by Lukasa** [comment] 2021-12-06 20:57
Duplicate of #162

**Closed by Lukasa** 2021-12-06 20:57 UTC
