### ISSUE TITLE
python __version__ is not matching pip package version

### ISSUE THREAD

**Issue by stankeB** [certifi/python-certifi#214] opened 2023-02-09 07:17 UTC
Hi guys,

thanks for your greate work on this python package.

I'm facing CVE scanning issues for your package, as the python __version__ string (2022.12.07) is not matching the pip package version of certifi (2022.12.7). CVE scanner are not recognizing the update, as the scanner check the __version__ string.

https://pypi.org/project/certifi/2022.12.7/
https://github.com/certifi/python-certifi/blob/master/certifi/__init__.py#L4

Is it possible to align this?

Thanks in advance!

**Comment by Lukasa** [comment] 2023-02-09 07:38
Dupe of #208. Our recommendation is that your scanner be fixed. pip normalizes the version strings, and whatever scanner you're using must do the same, or this kind of issue will pop up.

**Closed by Lukasa** 2023-02-09 07:38 UTC
