### ISSUE TITLE
certifi fails to recognise LetsEncrypt certificates since the root expiry

### ISSUE THREAD

**Issue by jribbens** [certifi/python-certifi#164] opened 2021-10-05 17:21 UTC
On CentOS 7.9, `requests` can fetch LetsEncrypt sites fine, but only if it's explicitly told *not* to use certifi's certificates:

```
Python 2.7.5 (default, Nov 16 2020, 22:23:17) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import certifi, requests
>>> certifi.__version__
'2021.05.30'
>>> requests.get('https://letsencrypt.org/', verify='/etc/pki/tls/certs/ca-bundle.crt')
<Response [200]>
>>> requests.get('https://letsencrypt.org/')                                    
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='letsencrypt.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)'),))
```

**Comment by alex** [comment] 2021-10-05 17:22
duplicate of #163

**Closed by alex** 2021-10-05 17:22 UTC

**Comment by jribbens** [comment] 2021-10-05 18:07
@alex I suspect you're going to continue to get duplicates while there is no open issue on this open issue...

**Comment by Lukasa** [comment] 2021-10-05 18:54
#163 is a dupe of #162 which is very much open.

**Comment by jribbens** [comment] 2021-10-05 20:02
#162 isn't an issue and thus doesn't shown on the project's "issues" list.
