### ISSUE TITLE
Upgraded to version 2023.7.22 and received an error on python 3.12.0b3

### ISSUE THREAD

**Issue by jschwar313** [certifi/python-certifi#233] opened 2023-08-04 11:05 UTC
I upgraded to certifi version 2023.7.22 and I received the following error.  I didn't change any other packages.  It was working before, but I received a GitHub notice about a security error.  Here's the stack trace:

Traceback (most recent call last):
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\util\ssl_.py", line 402, in ssl_wrap_socket
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\httpsession.py", line 465, in send
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 798, in urlopen
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\util\retry.py", line 525, in increment
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\packages\six.py", line 770, in reraise
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 714, in urlopen
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 403, in _make_request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 1053, in _validate_conn
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connection.py", line 419, in connect
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\util\ssl_.py", line 404, in ssl_wrap_socket
urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aws_pc_backup_main.py", line 708, in init python.aws_pc_backup_main
  File "aws_pc_backup_main.py", line 654, in python.aws_pc_backup_main.main
  File "aws_pc_backup_main.py", line 310, in python.aws_pc_backup_main.upload
  File "aws_pc_backup_main.py", line 231, in python.aws_pc_backup_main.copy_to_s3
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\boto3\s3\transfer.py", line 292, in upload_file
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\futures.py", line 103, in result
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\futures.py", line 266, in result
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 714, in urlopen
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 415, in _make_request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connection.py", line 244, in request
  File "http\client.py", line 1320, in request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 94, in _send_request
  File "http\client.py", line 1366, in _send_request
  File "http\client.py", line 1315, in endheaders
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 130, in _send_output
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 176, in _handle_expect_response
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 209, in _send_message_body
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 218, in send
  File "http\client.py", line 1031, in send
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\utils.py", line 511, in read
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\upload.py", line 90, in read
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 714, in urlopen
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 415, in _make_request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connection.py", line 244, in request
  File "http\client.py", line 1320, in request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 94, in _send_request
  File "http\client.py", line 1366, in _send_request
  File "http\client.py", line 1315, in endheaders
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 130, in _send_output
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 176, in _handle_expect_response
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 209, in _send_message_body
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 218, in send
  File "http\client.py", line 1031, in send
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\utils.py", line 511, in read
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\upload.py", line 90, in read
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 714, in urlopen
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 415, in _make_request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connection.py", line 244, in request
  File "http\client.py", line 1320, in request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 94, in _send_request
  File "http\client.py", line 1366, in _send_request
  File "http\client.py", line 1315, in endheaders
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 130, in _send_output
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 714, in urlopen
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 415, in _make_request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connection.py", line 244, in request
  File "http\client.py", line 1320, in request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 94, in _send_request
  File "http\client.py", line 1366, in _send_request
  File "http\client.py", line 1315, in endheaders
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 130, in _send_output
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 176, in _handle_expect_response
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 209, in _send_message_body
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 218, in send
  File "http\client.py", line 1031, in send
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\utils.py", line 511, in read
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\upload.py", line 90, in read
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 714, in urlopen
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connectionpool.py", line 415, in _make_request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\urllib3\connection.py", line 244, in request
  File "http\client.py", line 1320, in request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 94, in _send_request
  File "http\client.py", line 1366, in _send_request
  File "http\client.py", line 1315, in endheaders
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 130, in _send_output
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 176, in _handle_expect_response
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 209, in _send_message_body
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 218, in send
  File "http\client.py", line 1031, in send
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\utils.py", line 511, in read
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\upload.py", line 90, in read
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 176, in _handle_expect_response
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 209, in _send_message_body
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\awsrequest.py", line 218, in send
  File "http\client.py", line 1031, in send
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\utils.py", line 511, in read
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\upload.py", line 90, in read
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\tasks.py", line 139, in __call__
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\tasks.py", line 162, in _execute_main
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\s3transfer\upload.py", line 787, in _main
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\client.py", line 530, in _api_call
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\client.py", line 947, in _make_api_call
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\client.py", line 970, in _make_request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\endpoint.py", line 119, in make_request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\endpoint.py", line 202, in _send_request
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\endpoint.py", line 354, in _needs_retry
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\hooks.py", line 412, in emit
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\hooks.py", line 256, in emit
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\hooks.py", line 239, in _emit
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\retryhandler.py", line 207, in __call__
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\retryhandler.py", line 284, in __call__
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\retryhandler.py", line 320, in _should_retry
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\retryhandler.py", line 363, in __call__
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\retryhandler.py", line 247, in __call__
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\retryhandler.py", line 416, in _check_caught_exception
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\endpoint.py", line 281, in _do_get_response
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\endpoint.py", line 377, in _send
  File "C:\Program Files\Jim Schwartz\AWS PC Backup\packages\botocore\httpsession.py", line 492, in send
botocore.exceptions.SSLError: SSL validation failed for https://jschwar313-desktp-ufr9q1v-h-drive-backups.s3.us-east-2.amazonaws.com/%5CTemp_Download%5CH_Drive_Backup_20230803030006_6_1.rdr?uploadId=6hLA.vE5RXmzL9Fim8E10R3PFhW8tYB3e9mJ_3brjsEg5_SHJJd7OM5kg9EpqW.Co9nh5lfzh2l07DTggdjWUpAaywW1roBXGAnUizeIIIgSU3q8xqkz3uEfrlDKCUzf&partNumber=139 [Errno 2] No such file or directory

Here are my packages that I have installed:

(prod3120) H:\Users\LindaJim\Documents\SourceCode\Software\aws_pc_backup\src\c>pip list
Package            Version
------------------ ---------
attrs              23.1.0
boto3              1.26.160
botocore           1.29.160
certifi            2023.7.22
charset-normalizer 3.1.0
colorama           0.4.6
Cython             0.29.35
idna               3.4
iniconfig          2.0.0
jmespath           1.0.1
packaging          23.1
pip                23.1.2
pluggy             1.0.0
psutil             5.9.5
pytest             7.3.1
python-dateutil    2.8.2
requests           2.31.0
s3transfer         0.6.1
setuptools         68.0.0
six                1.16.0
urllib3            1.26.16

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by alex** [comment] 2023-08-04 12:35
Are you able to reproduce this issue in a new virtual environment?

This is almost 100% going to be an issue on your machine, as there are many many many users successfully using the latest version of this package.

**Comment by jschwar313** [comment] 2023-08-04 12:59
I'm using python version 3.12.0b3.  Do those many many users use that version?  I don't know whether to open this issue with you or the python developers.  Have you tested your package with the new release of python that's coming out in October yet?

**Comment by alex** [comment] 2023-08-04 13:02
a) Yes, we test with Python 3.12 in CI.
b) There's nothing in this package that would be impacted by Python 3.12.
c) If you look at the error message you're seeing, `FileNotFoundError: [Errno 2] No such file or directory`, this indicates to me that somehow your installation is corrupted and the path on disk doesn't exist.

**Comment by sigmavirus24** [comment] 2023-08-04 13:47
@jschwar313 I believe Alex is suggesting trying to reinstall certifi since it seems like the install was corrupted. The error suggests that the path `certifi.where()` returns does not exist and thus the upgrade of the package was not successful

**Comment by jschwar313** [comment] 2023-08-04 14:37
Ok.  I'll try that, too.  Sorry for my misunderstanding.

**Comment by jschwar313** [comment] 2023-08-05 13:29
How would I execute certifi.where() to make sure the package is installed correctly?

**Comment by jschwar313** [comment] 2023-08-05 13:30
nevermind.  I figured it out.  Sorry.

**Comment by jschwar313** [comment] 2023-08-05 16:46
I don't think that's it.  I'm using an embedded python distribution, so I can't just run a python script in it, but I created a python executable from a two line python script below and it works just fine.  Please let me know if this is a good test or not.  I'm sure you know this better than I do.  Here's the script:

import certifi
print(str(certifi.where()))

Here's the output from my application directory running the executable using the embedded distribution:

C:\Users\jschw\OneDrive\Documents\AWS PC Backup>certifi_where
C:\Users\jschw\OneDrive\Documents\AWS PC Backup\packages\certifi\cacert.pem

**Comment by sigmavirus24** [comment] 2023-08-06 00:01
The better test is to try to use `os.stat` or read data from the path. If you can stat or open the file, the SSL module can use it

**Comment by jschwar313** [comment] 2023-08-06 15:59
I ran a .cmd file script from my application location, so it uses that version of certifi, and it worked.  When it runs, it sends an email and it reads a config file from that path to get the details on the account.  The email was sent and the log file was created indicating it was successful.  Is that a good test?  Thanks for the help.

**Comment by sigmavirus24** [comment] 2023-08-07 13:28
Whatever test best helps ensure your use case will work is the best test. It seems things are working for you so I'm closing this issue.

**Closed by sigmavirus24** 2023-08-07 13:28 UTC
